### ISSUE TITLE
len plen issue during build

### ISSUE THREAD

**Issue by dkatzdev** [MotoX-2015/android_device_motorola_clark#19] opened 2015-10-02 13:14 UTC
Please merge commit 715f501ed310248f9522ed9113b31b23cea52e8b from somcom3x's repo. It fixes the len and plen issue in android_filesystem_config.h.

**Comment by rabih** [comment] 2015-10-02 13:26
The issue is your compiler, change it from gcc-multilib to gcc, as you'll
get more issues down the line.

**Comment by dkatzdev** [comment] 2015-10-03 04:48
N00b question, but how do I specify the C compiler to use without actually uninstalling the alternatives?

**Comment by rabih** [comment] 2015-10-03 11:41
Depending on your development environment, it's different. As I use arch
Linux, it's a different procedure than say Ubuntu. But since you're on
Ubuntu, it's something along the lines of sudo PROGRAMNAME
--update-alternatives. I'm not 100% positive as I haven't run Ubuntu in
years.

**Comment by dkatzdev** [comment] 2015-10-05 16:25
I wasn't sure if update alternatives was the right way. Thanks

**Comment by sebirdman** [comment] 2015-10-21 04:02
thsi should be fixed in more recent builds after i ran into the issue myself.

**Closed as completed by sebirdman** 2015-10-21 04:02 UTC
